on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch: {}

name: build-and-deploy-shinylive

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: "Check out"
        uses: actions/checkout@v4
      - name: "Setup R"
        uses: r-lib/actions/setup-r@v2
      - name: "Setup R dependencies"
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            cran::shinylive@0.9.0
      - name: Create R Shinylive App
        shell: Rscript {0}
        run: |
          shinylive::export(".", "_site")
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          retention-days: 1
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4